#n1 = int(input("Dugite um valor: "))
#n1 = float(input("Digite um valor:"))
#n1 = bool(input("Digite um valor: "))
#n1 = str(input("Digite um valor: "))
n1 = input("Digite algo: ")
# print(n1.isnumeric())
#print(n1.isalpha())
#print(n1.isalnum())
#print(n1.isupper())
print("È {}".format(type(n1)))
